### ISSUE TITLE
Asking for a permission to modify the project

### ISSUE THREAD

**Issue by vsobotka** [turtle225/Battle-Brothers-Damage-Calculator#1]
Hi, thanks for this awesome project!

Just wanted to ask whether it's ok with you if I use it as a backend and put it up on the internet for easier use? I also had several enhancements in mind, but I am not sure how much free time I will have for this.

**Comment by turtle225** [comment]
Yes, I'm ok with it.

I saw your reddit post as well. I know that a lack of a user friendly GUI has turned some people off from trying to use the calculator. It is something I've wanted to add and tried to learn at one point, but it fell to the wayside and I hadn't gotten back to it.

If you want to give it a try then I'm all for it. If there's anything I could help with then the best way to reach me would probably be a DM/Chat on Reddit.
